"""ChannelMessagesMixin — message send and history retrieval.

Extracted from channel_service.py. Depends on ChannelHelpersMixin
for validation and broadcast methods.
"""

import logging
from datetime import datetime

from ..database import db
from ..models.agent import Agent
from ..models.message import Message, MessageType
from ..models.persona import Persona
from .channel_errors import ContentTooLongError

logger = logging.getLogger(__name__)


class ChannelMessagesMixin:
    """Message operations — send and get_history."""

    def send_message(
        self,
        slug: str,
        content: str,
        persona: Persona,
        agent: Agent | None = None,
        message_type: str = "message",
        attachment_path: str | None = None,
        source_turn_id: int | None = None,
        source_command_id: int | None = None,
    ) -> Message:
        """Send a message to a channel.

        Args:
            slug: Channel slug.
            content: Message text content.
            persona: Sending persona.
            agent: Optional agent instance.
            message_type: One of 'message', 'delegation', 'escalation'.
            attachment_path: Optional file path.
            source_turn_id: Optional source turn FK.
            source_command_id: Optional source command FK.

        Returns:
            The created Message.

        Raises:
            ChannelNotFoundError: If channel not found.
            ChannelClosedError: If channel is complete/archived.
            NotAMemberError: If sender is not an active member.
            ValueError: If message_type is 'system'.
        """
        if message_type == "system":
            raise ValueError(
                "System messages are generated by the service, not callable directly."
            )

        # Content length validation
        max_len = (
            self.app.config.get("APP_CONFIG", {})
            .get("channels", {})
            .get("max_message_content_length", 50000)
        )
        if len(content) > max_len:
            raise ContentTooLongError(
                f"Error: Message content exceeds maximum length "
                f"({len(content):,} > {max_len:,} characters)."
            )

        # Attachment path validation
        if attachment_path is not None:
            self._validate_attachment_path(attachment_path)

        channel = self.get_channel(slug)
        self._check_closed(channel)
        self._check_membership(channel, persona, require_active=True)

        mt = MessageType(message_type)
        message = Message(
            channel_id=channel.id,
            persona_id=persona.id,
            agent_id=agent.id if agent else None,
            content=content,
            message_type=mt,
            attachment_path=attachment_path,
            source_turn_id=source_turn_id,
            source_command_id=source_command_id,
        )
        db.session.add(message)

        # Pending -> active on first non-system message
        if channel.status == "pending":
            self._transition_to_active(channel)

        db.session.commit()

        self._broadcast_message(message, channel)

        # Deliver to agent members via tmux (post-commit side effect)
        delivery_service = self.app.extensions.get("channel_delivery_service")
        if delivery_service:
            delivery_service.deliver_message(message, channel)

        return message

    def get_history(
        self,
        slug: str,
        persona: Persona,
        limit: int = 50,
        since: str | None = None,
        before: str | None = None,
    ) -> list[Message]:
        """Get message history for a channel.

        Args:
            slug: Channel slug.
            persona: Calling persona (must be a member: active, left, or muted).
            limit: Maximum messages to return.
            since: ISO timestamp — return messages after this time.
            before: ISO timestamp — return messages before this time.

        Returns:
            List of Message instances in chronological order.

        Raises:
            ChannelNotFoundError: If channel not found.
            NotAMemberError: If caller is not a member (any status).
        """
        channel = self.get_channel(slug)
        # Allow active, left, and muted members to read history
        self._check_membership(channel, persona, require_active=False)

        query = Message.query.filter_by(channel_id=channel.id)

        if since:
            since_dt = datetime.fromisoformat(since)
            query = query.filter(Message.sent_at > since_dt)

        if before:
            before_dt = datetime.fromisoformat(before)
            query = query.filter(Message.sent_at < before_dt)

        # Fetch the *newest* messages up to `limit`, then reverse so the
        # caller receives them in chronological (oldest-first) order.
        # Without this, limit=50 on a 200-message channel returns the
        # oldest 50 — hiding all recent conversation.
        rows = query.order_by(Message.sent_at.desc()).limit(limit).all()
        rows.reverse()
        return rows
