"""Add domain models: Objective, Project, Agent, Task, Turn, Event

Revision ID: 5c4d4f13bcfb
Revises: 
Create Date: 2026-01-29 10:08:18.855919

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5c4d4f13bcfb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objectives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_text', sa.Text(), nullable=False),
    sa.Column('constraints', sa.Text(), nullable=True),
    sa.Column('set_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('github_repo', sa.Text(), nullable=True),
    sa.Column('current_branch', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_uuid', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('iterm_pane_id', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_agents_project_id_last_seen_at', ['project_id', 'last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_session_uuid'), ['session_uuid'], unique=True)

    op.create_table('objective_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objective_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('constraints', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('objective_histories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_objective_histories_objective_id'), ['objective_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('IDLE', 'COMMANDED', 'PROCESSING', 'AWAITING_INPUT', 'COMPLETE', name='taskstate', create_constraint=True), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index('ix_tasks_agent_id_state', ['agent_id', 'state'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_state'), ['state'], unique=False)

    op.create_table('turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.Enum('USER', 'AGENT', name='turnactor', create_constraint=True), nullable=False),
    sa.Column('intent', sa.Enum('COMMAND', 'ANSWER', 'QUESTION', 'COMPLETION', 'PROGRESS', name='turnintent', create_constraint=True), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('turns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turns_task_id'), ['task_id'], unique=False)
        batch_op.create_index('ix_turns_task_id_timestamp', ['task_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_turns_timestamp'), ['timestamp'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('turn_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index('ix_events_agent_id_timestamp', ['agent_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index('ix_events_event_type_timestamp', ['event_type', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_events_project_id_timestamp', ['project_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_turn_id'), ['turn_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_turn_id'))
        batch_op.drop_index(batch_op.f('ix_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_events_task_id'))
        batch_op.drop_index('ix_events_project_id_timestamp')
        batch_op.drop_index(batch_op.f('ix_events_project_id'))
        batch_op.drop_index('ix_events_event_type_timestamp')
        batch_op.drop_index(batch_op.f('ix_events_event_type'))
        batch_op.drop_index('ix_events_agent_id_timestamp')
        batch_op.drop_index(batch_op.f('ix_events_agent_id'))

    op.drop_table('events')
    with op.batch_alter_table('turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turns_timestamp'))
        batch_op.drop_index('ix_turns_task_id_timestamp')
        batch_op.drop_index(batch_op.f('ix_turns_task_id'))

    op.drop_table('turns')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_state'))
        batch_op.drop_index('ix_tasks_agent_id_state')
        batch_op.drop_index(batch_op.f('ix_tasks_agent_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('objective_histories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_objective_histories_objective_id'))

    op.drop_table('objective_histories')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_session_uuid'))
        batch_op.drop_index('ix_agents_project_id_last_seen_at')
        batch_op.drop_index(batch_op.f('ix_agents_project_id'))

    op.drop_table('agents')
    op.drop_table('projects')
    op.drop_table('objectives')
    # ### end Alembic commands ###
